//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPLICATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverLicenseCategory
    {
        public int Id { get; set; }
        public int DriverLicenseId { get; set; }
        public int DriverLicenseCategoryId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual DriverLicenseCategories DriverLicenseCategories { get; set; }
        public virtual DriverLicenses DriverLicenses { get; set; }
    }
}
