//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPLICATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        public System.Guid Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Passport { get; set; }
        public string RegAddress { get; set; }
        public string LiveAddress { get; set; }
        public string PlaceOfWork { get; set; }
        public string WorkPosition { get; set; }
        public string PhoneMobile { get; set; }
        public string Email { get; set; }
        public int PhotoId { get; set; }
        public string Remarks { get; set; }
    
        public virtual Photos Photos { get; set; }
    }
}
