//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPLICATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class FineStatusHistory
    {
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int FineId { get; set; }
        public int FineStatusId { get; set; }
    
        public virtual Fines Fines { get; set; }
        public virtual FineStatuses FineStatuses { get; set; }
    }
}
