//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPLICATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionCodeCodes
    {
        public int Id { get; set; }
        public int RegionCodeId { get; set; }
        public int Code { get; set; }
    
        public virtual RegionCodes RegionCodes { get; set; }
    }
}
