//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPLICATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionCodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegionCodes()
        {
            this.RegionCodeCodes = new HashSet<RegionCodeCodes>();
        }
    
        public int Id { get; set; }
        public string RegionNameEN { get; set; }
        public string RegionNameRU { get; set; }
        public Nullable<int> SubjectCode { get; set; }
        public string OKATOCode { get; set; }
        public string ISO3166_2Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegionCodeCodes> RegionCodeCodes { get; set; }
    }
}
