//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPLICATION
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegNumbers
    {
        public int Id { get; set; }
        public int VehicleId { get; set; }
        public int RegionCodeCodeId { get; set; }
        public string Series { get; set; }
        public int Number { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual RegionCodeCodes RegionCodeCodes { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
